# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UyecFtB_pqDFjpAu3ECJQEhIIXDyOeiH

**Importing the necessary libraries.**
"""

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import plotly 
import plotly.express as px
import pandas as pd
import numpy as np

#Data Visulation
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

from datetime import datetime

import statsmodels.api as sm
    
from warnings import filterwarnings
filterwarnings("ignore")

"""**Uploading the dataset and naming it df.**"""

df = pd.read_csv("NetflixOriginals.csv", encoding=("ISO-8859-1") ,sep = ",")

"""**Lets take a look at our data.**"""

df

"""**Using ".head()" allows us the see the first five row of our data. Five is the default number. We can specify this number by writing it in the paranthesis.**"""

df.head()

"""**Using ".tail()" allows us the see the last five row of our data. Five is the default number. We can specify this number by writing it in the paranthesis.**"""

df.tail()

"""**Lets start our analysis according the given questions.**

# 1- [TR]Veri setine göre uzun soluklu filmler hangi dilde oluşturulmuştur?
#Görselleştirme yapınız. 
#[ENG]In which language were the long-run movies were created according to the dataset? Visualize it.

For this question, first we need to determine the limit for long-run movies. Lets select 90 which equals to 1 and a half hour and find out which movies suits this spesification.
"""

long_run = df[df["Runtime"] >= 120]
long_run

"""Now that we have found the long run movies, we need to find in which language they are and how many are there for each language. For this, we are going to use ".groupby()"
"""

long_run_language = long_run.groupby("Language")["Runtime"].count().sort_values(ascending=False)
long_run_language

"""For visualization, I will go with pie chart. """

long_run_pie = go.Figure(data=[go.Pie(labels=df[df["Runtime"]>=120]["Language"].value_counts().index, 
                             values=df[df["Runtime"]>=120]["Language"].value_counts().values, hole=.4)])
long_run_pie.update_layout(title="Languages of movies lasting more than 2 hours",title_x=0.5,legend_title="Languages",font=dict(family="Lucida Grande",size=15,color="sienna"))
long_run_pie.show()